version: '3.8'

services:
  jenkins:
    build:
      context: .
    container_name: local-jenkins
    restart: unless-stopped
    network_mode: host
    volumes:
      - jenkins_home:/var/jenkins_home
      - ../../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/var/jenkins_home/.kube:ro
      - ${HOME}/.minikube:${HOME}/.minikube:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8081
      - KUBECONFIG=/var/jenkins_home/.kube/config

volumes:
  jenkins_home:
